### ISSUE TITLE
create new section which will solve nth-highest problems

### ISSUE THREAD

**Issue by sagarbee** [PranabKumarSahoo/sql-dev-tools#11]
create new section which will solve nth-highest problems. it will take column name, table name and nth highest as input from user and then after submit click will find nth highest . for example- let column name = sal, table name=emp and nth highest = 4 then -> it will print select sal from(select rownum srno, sal from (select distinct sal from emp order by sal desc))where srno = 4;

![Screenshot (141)](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/65588552/c6c83341-3d90-4190-bfe9-5228098095c3)
![Screenshot (140)](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/65588552/d99ef05d-ff11-4aae-9980-da29a95e078a)

**Comment by PranabKumarSahoo** [comment]
Hello @sagarbee,
Thank you for creating an issue! ⭐ 

You've got some fantastic idea for adding this new feature.
So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 
Please keep me updated on your progress through images/videos in the comment section before raising the PR.

**PS: Always mention the issue number in your PR in the following format: Resolve issue #<issue_number>**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px). 

**#Good luck! ✌️**

**Comment by sagarbee** [comment]
Apologies for not using the correct format (Resolve issue #<issue_number>) in my issue report and for not providing progress updates with images/videos as instructed. I'll ensure to adhere to the guidelines moving forward. Thank you for your understanding.

**Comment by sagarbee** [comment]
@PranabKumarSahoo shoul i close this issue as it is merge

**Comment by PranabKumarSahoo** [comment]
Sure @sagarbee!
Don't worry I'll close this. 😉✌️

Feel free to contribute on another issues.

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px). 

**#Good luck! ✌️**
