### ISSUE TITLE
Creating Scroll up button in Home page to go to top

### ISSUE THREAD

**Issue by sagarbee** [PranabKumarSahoo/sql-dev-tools#12]
Creating Scroll up button in Home page to go to top.

**Comment by PranabKumarSahoo** [comment]
Hello @sagarbee,
Thank you for creating an issue! ⭐ 

So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 
Please keep me updated on your progress through images/videos in the comment section before raising the PR.

**PS: Always mention the issue number in your PR in the following format: Resolve issue #<issue_number>**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px). 

**#Good luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
This issue is Solved.
So I closed this. ⭐

**Thanks for the contribution! ✌️**
