### ISSUE TITLE
create new section which will solve nth-smallest problems

### ISSUE THREAD

**Issue by sagarbee** [PranabKumarSahoo/sql-dev-tools#14]
For example suppose we want to find 2nd minimum salary of employee then we need to 1 minimum and next minimum will be greater than first minimum. 

can be solved using two solution :
1. using subquery
2. using psudo columns

i will try to implement(show in output box) in both ways if possible.

**Comment by PranabKumarSahoo** [comment]
Hello @sagarbee,
Thank you for creating an issue! ⭐ 

Nice feature!
So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 
Please keep me updated on your progress through images/videos in the comment section before raising the PR.

**PS: Always mention the issue number in your PR in the following format: Resolve issue #<issue_number>**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px). 

**#Good luck! ✌️**

**Comment by sagarbee** [comment]
@PranabKumarSahoo please review the solution i had made for above issue.

https://github.com/PranabKumarSahoo/sql-dev-tools/assets/65588552/afb43452-d19e-49bb-9e9a-37cb31283a29

**Comment by PranabKumarSahoo** [comment]
Nice work @sagarbee! ⭐

Have you tested the query!! Can you show me the test query! How it works?

**Comment by sagarbee** [comment]
@PranabKumarSahoo 

https://github.com/PranabKumarSahoo/sql-dev-tools/assets/65588552/a41f893a-c1f2-433e-9464-0c5770c49e78

**Comment by sagarbee** [comment]
innermost query is executed first. The innermost query retrieves distinct values of the "sal" column from the "emp" table and orders them in ascending order. Then, the middle query assigns row numbers (ROWNUM) to each result.

After that, the outermost query selects the "sal" column from the result where the row number (srno) is equal to 4.

**Comment by PranabKumarSahoo** [comment]
Good job @sagarbee,

That's really interesting feature. You can raise the PR.✌️

**Comment by PranabKumarSahoo** [comment]
As this feature is merged to the main branch!

So, I'm closing this issue now.

**Thanks for the contribution. ⭐**

---

**#Good luck! ✌️**
