### ISSUE TITLE
[BUG] : Problem in the UI of the 'Count of Rows' Section

### ISSUE THREAD

**Issue by SulagnaKundu** [PranabKumarSahoo/sql-dev-tools#18]
## Describe the bug:
In the 'Count of Rows' section, the UI needs to be fixed.

## To Reproduce:
1. Go to the Home Page
2. Scroll down to find the 'Count of Rows' heading
3. UI needs to be fixed

## Screenshots
![image](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/103977344/7f8f19eb-0ec9-4ef6-9a3d-7b7ba7d8d2ba)

**Comment by PranabKumarSahoo** [comment]
Hello @SulagnaKundu,
Thank you for creating an issue! ⭐ 

So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 
Please keep me updated on your progress through images/videos in the comment section before raising the PR.

**PS: Always mention the issue number in your PR in the following format: Resolve issue #<issue_number>**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px). 

**#Good luck! ✌️**

**Comment by SulagnaKundu** [comment]
I think , I have fixed the issue on the count of rows section that was there previously. Please have a look at the screenshot attached-
![image](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/103977344/dd216618-2bda-4e92-97c9-e0f06d482e20)
Shall I raise a PR right now ?

**Comment by PranabKumarSahoo** [comment]
Good job @SulagnaKundu! ⭐

Have you checked for all the devices!!?
If it's then you can raise the PR.

**Thanks for the Contribution.**

---
**#Good Luck! ✌️**

**Comment by SulagnaKundu** [comment]
Yes, I have checked for all the devices and I think it works fine.
