### ISSUE TITLE
Add Toastify Notification on Submit Button Click.

### ISSUE THREAD

**Issue by PranabKumarSahoo** [PranabKumarSahoo/sql-dev-tools#2]
## Feature Request

I suggest adding a **Toastify Notification** when the **Submit Button** is clicked. This notification can be used to provide feedback to the user, such as confirming that the query has been submitted or that the query has been copied.

---
**#Additional Information:**
- If there are specific elements or sections that need improvement, mention them by making new issues.
- Consider attaching images to illustrate your suggestions.

Please leave a comment on this, then I'll try to assign the task accordingly.
If your contribution is well-received, I encourage you to submit a Pull Request with the changes.

### Feel free to ask questions or seek clarification on any aspect of the improvements.

**#Good Luck! ✌️**

**Comment by Anubhab-03** [comment]
I want to contribute and implement the Toastify notification feature. Kindly assign it to me under SWOC'24.

**Comment by PranabKumarSahoo** [comment]
Hello @Anubhab-03, 
Thanks for your interest in this issue.⭐

Here's my concern,
- As per the **SWOC rules**, we **(Project Admins)** can assign the tasks to the **Contributors** from 1st of Jan.
- But you can work on this now and keep me update your output through images/videos in the comment section. 
- And one more thing, don't make any PR now, you can do it when the program begins (On 1st Jan).

So don't worry, I'll assign this task to you with the tag on 1st of Jan.

Hope you got my points!

Thanks For Understanding! ✌️

---
### Feel free to ask any questions for further clarification.
**#Good Luck!✌️**

**Comment by Anubhab-03** [comment]
Got it @PranabKumarSahoo

**Comment by PranabKumarSahoo** [comment]
@Anubhab-03,

Today is the 1st of Jan. So, I'm officially assigning this task to you! 
So feel free to start working on it. 
Please keep me updated on your progress through images/videos in the comment section.

For real-time communication and any immediate queries, you can join the [Discord](https://discord.gg/TSYH66px).

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on Discord. 

**#Good luck! ✌️**

**Comment by ayann07** [comment]
I would like to work on this issue under SWOC 2024.

**Comment by PranabKumarSahoo** [comment]
Hello @ayann07,
Thanks for your interest in this issue!

- The **Toastify Notification** feature task has already been assigned to @Anubhab-03 on a FCFS(first-come, first-served) basis under **SWOC**.
- But I assign this to you also. So start working on this. Remember to make your changes and keep me update your progress through images/videos in the comment section.

### I'll be merge the first submission! 😉

For real-time communication and any immediate queries, you can join the [Discord](https://discord.gg/TSYH66px).

---
### Feel free to ask any questions for further clarification.
**#Good Luck!✌️**

**Comment by PranabKumarSahoo** [comment]
Hello @ayann07,

I wanted to inform you that the **Toastify Notification** feature task has been successfully implemented by @Anubhab-03, and the pull request has been submitted. Great job, @Anubhab-03! 

Given that the task has been completed, I am closing this issue now. Thank you for your interest in contributing! 

Your participation is highly valued, and I look forward to your continued contributions.

---
If you have any questions, need clarification, or would like to work on another task, feel free to let me know.

**#Good luck! ✌️**
