### ISSUE TITLE
[DOCS]: Create a CONTRIBUTING.md file for the project

### ISSUE THREAD

**Issue by singodiyashubham87** [PranabKumarSahoo/sql-dev-tools#25]
You have to make a CONTRIBUTING.md markdown file guiding the contributors upon how to contribute to the repository, mention all the necessary steps & best practices for commits, branching, etc.

**Comment by ARSHIA03** [comment]
Hey I am making this md file

**Comment by PranabKumarSahoo** [comment]
> You have to make a CONTRIBUTING.md markdown file guiding the contributors upon how to contribute to the repository, mention all the necessary steps & best practices for commits, branching, etc.

Hello @singodiyashubham87, Thank you for opening this issue and providing guidance on creating a **CONTRIBUTING.md** file. 
I appreciate the initiative! ✌️

**Comment by PranabKumarSahoo** [comment]
> Hey I am making this md file

Hello @ARSHIA03, I'm officially assign this to you under **SWOC**.

Thank you for your dedication in creating the **CONTRIBUTING.md** file. Your contribution is highly appreciated. 
As you work on the file, I kindly request you to review other open/closed issues for potential clarifications and analyze the communication provided to contributors about project guidelines. 

Ensuring consistency and clarity in our guidelines will greatly benefit the project. If you have any questions or require further details, please don't hesitate to reach out.

Thanks again for the contribution! ⭐

---
**#Good luck! ✌️**
