### ISSUE TITLE
add a feature button for dark or light theme

### ISSUE THREAD

**Issue by Komal73** [PranabKumarSahoo/sql-dev-tools#26]

**Comment by Komal73** [comment]
@PranabKumarSahoo kindly assign this issue under SWOC 24

**Comment by PranabKumarSahoo** [comment]
Hello @Komal73,
Thank you for creating an issue! ⭐ 

Dark/Light Mode! That's a cool idea for users-experience. 
So, I'm officially assigning this task to you under **SWOC**.

Here're some of my concerns,
- Regarding the implementation of the dark/light mode feature, could you provide an overview on your approach? 
- Specifically, If you're planning to use local storage to ensure a seamless experience for users, where the selected mode persists even after a page refresh!! 
- This could enhance the user experience, and your insights on the implementation approach would be valuable.
- Please share your approach before working on it, It'd be better.

Please keep me updated on your progress through images/videos in the comment section before raising the PR.

**PS: Always mention the issue number in your PR in the following format: Resolve issue #<issue_number>**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel]. 

**#Good luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
Hello @Komal73! ⭐

What's your work progress!!! Please update here.

**Comment by Komal73** [comment]
I am encountering some error and resolving it

**Comment by PranabKumarSahoo** [comment]
Hello @Komal73,

Thank you for letting me know. Take your time to resolve the issues, and if you need any assistance or guidance during the process, feel free to reach out. It's totally normal to encounter challenges, and addressing them is part of the development journey.

If there's anything specific you'd like help with or if you want to share more details about the errors you're facing, please do so. I'm here to support you in making progress.

Looking forward to your updates, and don't hesitate to ask if you have any questions.

---
**#Good Luck!✌️**

**Comment by Komal73** [comment]
Hi @PranabKumarSahoo , thank you for your support. Actually while applying light theme in every section there is some space left to be colored under light theme...and I'm unable to understand why is this so..

![Screenshot 2024-01-16 133118](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/115211296/5f16e15c-3195-4b7e-ac62-d21379b983f1)

the count of rows is not in light theme

**Comment by PranabKumarSahoo** [comment]
Hello @Komal73, Thanks for letting me know about this issue. 
Actually, I'm quite busy in day time. So don't worry, I'll review this issue in evening.

**Comment by PranabKumarSahoo** [comment]
Hello @Komal73,

Regarding the issue, it seems like there might be a specific styling concern causing the misalignment in the "Count of Rows" section under the light theme or there might be anything else. To better assist you, could you provide a bit more detail or share relevant code snippets related to that section?

Feel free to share any video reference of the code, and I'll do my best to help identify and address the issue.

**Comment by Komal73** [comment]
@PranabKumarSahoo I'll share you the code snippet tomorrow after my semester exam.

**Comment by Komal73** [comment]
![Screenshot 2024-01-19 121804](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/115211296/9582f548-53d5-46cc-9ec4-cade68df4e3a)

This is the screenshot of the div of count of rows section.

**Comment by PranabKumarSahoo** [comment]
@Komal73, Thank you for providing the screenshot. However, for a more comprehensive understanding of the issue, it would be helpful if you could provide additional details. Please consider sharing:

- Please make a proper video of that section as well as the code snippet of light/dark mode. 
- If you implemented the light/dark mode using `useContext`, please include snippets or references related to that.
- And also show the every particular section in which you added this light/dark mode code context.

This information will assist in diagnosing the issue more effectively, and I'll be better equipped to provide guidance or suggestions.

Take your time, and if you have any questions, feel free to ask.

**Comment by Parth4git** [comment]
I had work on this feature before .So, I wanted to work on this issue . @PranabKumarSahoo

**Comment by Komal73** [comment]
@PranabKumarSahoo I got the error it is in the h2 tag of each component. 
![Screenshot 2024-01-21 172026](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/115211296/251b2986-aaa5-418c-8297-409d6eabe863)

**Comment by Komal73** [comment]
@PranabKumarSahoo there is an error, while on dark theme and refreshing, the changes gets saved but the button changes to light theme. I've attached references.

https://github.com/PranabKumarSahoo/sql-dev-tools/assets/115211296/d4fd4dec-9ce5-42e0-be85-72e78f4ccce3



https://github.com/PranabKumarSahoo/sql-dev-tools/assets/115211296/5b1772b4-699e-47db-bd03-91a2ee9e12fb

**Comment by PranabKumarSahoo** [comment]
There's one approach in my mind;
You should store checked property in localStorage & according to checked property, you can set the Sun & Moon icon.

**Comment by Komal73** [comment]
@PranabKumarSahoo Thank you, it is working fine now. I learned it very well. I'm making a PR now.

**Comment by Parth4git** [comment]
@PranabKumarSahoo Can I work on this issue
