### ISSUE TITLE
[Feat]: Improve Side Navbar Interaction for Consistent Closing Behavior

### ISSUE THREAD

**Issue by PranabKumarSahoo** [PranabKumarSahoo/sql-dev-tools#30]
## Issue: Improve Side Navbar Interaction

**Description:**
- The current behavior of the side navbar could be improved to enhance user experience and ensure consistency. 
- Currently, the sidebar opens and closes when clicking the button in the top left corner. 
- However, there is an issue when clicking outside the button or outside the navbar area; it does not close the sidebar.

**Expected Behavior:**
- The sidebar should close when clicking outside the button or outside the navbar area.

**Steps to Reproduce:**
1. Click the button to open the sidebar.
2. Click outside the button or navbar area.
3. Observe that the sidebar remains open, which is unexpected.

**Additional Information:**
- Consider implementing a mechanism where clicking outside the button or navbar area triggers the closing of the sidebar.
- Ensure that the transition is smooth and provides a seamless user experience.

Please leave a comment on this, then I'll try to assign the task accordingly.
If your contribution is well-received, I encourage you to submit a Pull Request with the changes.

---
Feel free to ask questions or seek clarification on any aspect.

**#Good Luck!✌️**

**Comment by Girishbari** [comment]
assign me, let me see what I can do

**Comment by PranabKumarSahoo** [comment]
Hello @Girishbari,

Thank you for your interest to work on improving the side navbar interaction! Your enthusiasm is much appreciated.

So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 
Please keep me updated on your progress through images/videos in the comment section before raising the PR.

**PS: Always mention the issue number in your PR in the following format: Resolve issue #<issue_number>**

Make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md).

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
Cool @Girishbari,
Thanks for your contribution. I appreciate your work.⭐

But I kindly request that for future tasks, please wait until the task is officially assigned to you before starting the work. This process helps in maintaining clarity and provides a structured approach to our tasks.

Thank you for your understanding and cooperation.

Make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md).
