### ISSUE TITLE
Add the contact us page

### ISSUE THREAD

**Issue by parmesh-bhatt** [PranabKumarSahoo/sql-dev-tools#31]
In official website, the contact us page doesn't exits. I want to add this.

**Comment by parmesh-bhatt** [comment]
I am working on this issue.

**Comment by PranabKumarSahoo** [comment]
Hello @Parmesh119,

Thank you for taking the initiative to address the need for a "**Contact Us**" page on our official website. Your contribution is much appreciated. So, I'm officially assigning this task to you under **SWOC**.

But I kindly request that for future tasks, please wait until the task is officially assigned to you before starting the work. This process helps in maintaining clarity and provides a structured approach to our tasks.

Thank you for your understanding and cooperation.

Make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md).

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
Hello @Parmesh119,

Thank you for your contribution.

I want make a friendly reminder for you.
As per our  [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md), it would be helpful if you could provide a visual representation through images or videos in the comment section. This ensures a clearer understanding of the modifications made. Please try to submit a visual before raising the PR.

Your adherence to the contribution guidelines is highly appreciated, and I look forward to your updates on the pull request.

**#Good Luck! ✌️**

**Comment by parmesh-bhatt** [comment]
Screen shot
![Contact](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/101285245/9596e5bf-abec-42a3-9216-79193fc9a70d)

**Comment by PranabKumarSahoo** [comment]
Hello @Parmesh119,

I've reviewed the changes you made, and the UI looks good. However, considering our website's overall dark mode, it would enhance the user experience if the "Contact Us" page aligns with the dark mode theme.

I recommend making adjustments to ensure the page follows the same color scheme as the rest of our website. This consistency will contribute to a seamless user interaction.

Thank you for your understanding and dedication to improving our project.

---
**#Good Luck!✌️**

**Comment by PranabKumarSahoo** [comment]
This is to inform, that as of now we don't need **Contact Us** Page. So I'm closing this issue now.
I'll reopen whenever needed.

Thanks for the effort. I appreciate it.✌️
