### ISSUE TITLE
Overlapping of Count Rows and Drop Constraints section

### ISSUE THREAD

**Issue by kherkatary** [PranabKumarSahoo/sql-dev-tools#33]
# BUG : 
The answer section of Drop constraints and heading of Count Rows Overlaps 
### Steps to reproduce: - 
- Input large no of values
- Another way to check is to zoom the website

### NOTE: this is not a issue for smaller scaling of screens but will create problems if screen scaling is large. 

![issue-overlapping of sections](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/97865752/2d748a4e-8548-4184-9c44-6023d16eedb7)

**Comment by PranabKumarSahoo** [comment]
Hello @kherkatary,

Thank you for reporting this bug and providing the steps to reproduce. Your attention to detail is valuable for improving our project.

I understand the issue with the output section of "Drop constraints" and the heading of "Count Rows Overlaps" when using a large screen scaling or zooming the website. I appreciate your diligence in identifying this.

So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 

For the PR, Make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md).

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**

**Comment by kherkatary** [comment]
Thank You Sir

**Comment by PranabKumarSahoo** [comment]
Hello @kherkatary,

Thank you for your prompt action in submitting the pull request #34 to address the overlapping issue with "Drop constraints" and "Count Row."

As per our  [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md), it would be helpful if you could provide a visual representation of your changes through images or videos in the comment section. This ensures a clearer understanding of the modifications made. Please try to submit a visual before raising the PR.

Your adherence to the contribution guidelines is highly appreciated, and I look forward to your updates on the pull request.

**#Good Luck! ✌️**
