### ISSUE TITLE
add codeql for project

### ISSUE THREAD

**Issue by pinak22dhir** [PranabKumarSahoo/sql-dev-tools#35]
add codeql.yaml for better workflow

**Comment by PranabKumarSahoo** [comment]
Hello @pinak22dhir,

Thank you for suggesting the addition of a `codeql.yaml` for a better workflow. I see the value in this enhancement.

Before proceeding, could you please provide more details or any specific configuration preferences you have in mind for the `codeql.yaml` file? Once we have a clear understanding, I'll be happy to assign the task to you.

Your contribution to improving our project workflow is much appreciated.

**#Good Luck! ✌️**

**Comment by pinak22dhir** [comment]
1. To run this workflow you need to enable the following permission:
2. Go to your project repository settings
On left pane > Actions > General
image

3. Scroll down and Go to Workflow permissions > select "Read and write permissions"
image

4. Click save and its done.

**Comment by PranabKumarSahoo** [comment]
Hello @pinak22dhir,

Thank you for suggesting the addition of a `codeql.yaml` for a better workflow.
But we don't want that as of now. So, I've to close this issue. 
If needed, we can collaborate in future.

**Thanks for the effort & contribution.**
