### ISSUE TITLE
pr_issue_template

### ISSUE THREAD

**Issue by pinak22dhir** [PranabKumarSahoo/sql-dev-tools#36]
1.pr issue template for contributors to contribute it will make pr better for understanding of maintainer

**Comment by PranabKumarSahoo** [comment]
Hello @pinak22dhir,

Thank you for opening this issue! Your suggestion to create a PR issue template is excellent. It will indeed enhance the contribution process and provide clarity for both contributors and maintainers.

So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 

Make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md).

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**
