### ISSUE TITLE
[Feature]: add codeql workflow

### ISSUE THREAD

**Issue by harmeetsingh11** [PranabKumarSahoo/sql-dev-tools#40]
### Is your feature request related to a problem? Please describe. 

The repository contains code in `javascript`, it does not have workflow for code scanning. 

### Describe the solution you'd like 

I aim to implement the CodeQL workflow to automate security checks. CodeQL, GitHub's code analysis engine, will identify vulnerabilities in the code and present the findings as code scanning alerts. This workflow will be activated for every push, commit, and pull request through GitHub Actions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by PranabKumarSahoo** [comment]
Hello @harmeetsingh11, Thanks for creating this issue.

To ensure the effectiveness and clarity of our guidelines in implementing the `CodeQL` workflow, I would like to seek assistance from our mentor @singodiyashubham87 about this issue. Your insights and collaboration on this matter will be invaluable.

Thank You!✌️

**Comment by singodiyashubham87** [comment]
@PranabKumarSahoo We can assign the issue to @harmeetsingh11 .

**Comment by PranabKumarSahoo** [comment]
> @PranabKumarSahoo We can assign the issue to @harmeetsingh11 .

All right @singodiyashubham87, I appreciate your decision.

So @harmeetsingh11, I'm Officially assigning this to you. Please make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md).

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**
