### ISSUE TITLE
Style Issue: Overlapping of Input/ Output sections

### ISSUE THREAD

**Issue by KhushiRawat29** [PranabKumarSahoo/sql-dev-tools#41]
Destination:
1) Navigate to the official website
2) Scroll down a little to the "Count of rows" section.
3) Minimize the size of the window to "Tablet size".

Here you will observe the overlapping of Output section of "Drop constraint" and Input section of "Count of rows" . The heading titled "Count of rows" is also overlapping .
 The issue is directed to improve the styling of the sections for better appearance and user readability.

![2024-01-14 (11)](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/117963603/a19985d6-a6ca-4280-96b2-c105ae817a36)

@PranabKumarSahoo please assign this issue to me.

**Comment by PranabKumarSahoo** [comment]
Hello @KhushiRawat29,

Thank you for creating this issue.
I want to inform you that someone has already addressed and resolved this specific issue. If you clone the most recent version of the project and run the application, you'll find that the screen break you mentioned has been fixed.

Nevertheless, I appreciate your proactive approach and willingness to contribute. Your attention to detail and commitment to enhancing user experience are valuable contributions to our project.

If you have any other issues or if there's anything else you'd like to work on, feel free to let me know. 

Thank you again for your dedication. ⭐

----
**#Good Luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
I'm closing this issue now @KhushiRawat29. 

If you have any other issues or if there's anything else you'd like to work on, feel free to let me know.

---
**#Good Luck! ✌️**
