### ISSUE TITLE
Add footer section 

### ISSUE THREAD

**Issue by mansi1309** [PranabKumarSahoo/sql-dev-tools#45]
I would like to add footer section in this.
![image](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/133951716/66de8258-c303-49fb-b211-0dfa1f99646b)

**Comment by PranabKumarSahoo** [comment]
Hello @mansi1309,
Thank you for creating an issue on this! ⭐ 

So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it.

I want you to know that before create any issues, make sure to read the full documentation of this project first. It'll give you a better understanding.

Make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md) & [PR Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/pull_request_template.md).

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**

**Comment by Paarisha1** [comment]
Can I contribute in this

**Comment by PranabKumarSahoo** [comment]
Hello @Paarisha1,

Absolutely! If you're interested in working on the footer section for the SQL Dev Tools project, that would be fantastic.

Certainly! Before you start contributing, I recommend reviewing the pull request discussion on the related footer issue.

@mansi1309's pull request (#48) has some feedback and concerns regarding the codebase. Take some time to go through the discussion to understand the issues that were identified. This will help you in crafting your contributions more effectively and ensure alignment with the project's standards.

However, I'm officially assigning this task to you under **SWOC**.

Make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md) & [Pull Request Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/pull_request_template.md).

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**

**Comment by Paarisha1** [comment]
Sir what do you want me to add in footer section

**Comment by PranabKumarSahoo** [comment]
I'll provide you a simple footer design template, you can work on that by adding relevant links of our project in the footer list.

Here's the design:
**Desktop**

![FireShot Capture 213 - simple footer - codepen io](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/118038201/e826699f-0411-42e5-a9fa-cb53e297aed5)

**Mobile**

![FireShot Capture 214 - simple footer - codepen io](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/118038201/0587fd45-4c34-463d-a1cb-9b5a6337a1f8)

**Comment by Paarisha1** [comment]
Sure

**Comment by Shivam250702** [comment]
@PranabKumarSahoo 
I want to add the footer section just like mentioned above, please assign this issue to me

**Comment by PranabKumarSahoo** [comment]
Hello @Shivam250702,
Thanks for your interest in this issue!

As you can see, this task has already been assigned to @Paarisha1 with `Easy` label.

So, feel free to create another issues.
Thanks for understanding.

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
Hey @Paarisha1,

Thank you for the update on footer design. I appreciate your diligence.

However, upon further review, I've observed that the code changes in your PR might cause conflicts with the main branch. Additionally, there have been some recent feature additions to the main branch.

So, I kindly request you should clone the recent version of the repository and make the necessary changes accordingly. 
However, for the time being, I would advise waiting until further updates are provided before making any additional changes.

**Thank you for your understanding.** 

---
**PS: I will provide you with further updates soon. Till then don't do anything.**

**Comment by Paarisha1** [comment]
Sure sir

**Comment by Paarisha1** [comment]
Sir kindly provide me all the updates soon so that I can start working on this

**Comment by PranabKumarSahoo** [comment]
@Paarisha1, I've merged your PR as it has no conflict in the current situation.

Thank you for the Contribution.✌️
