### ISSUE TITLE
Enhance Side bar 

### ISSUE THREAD

**Issue by Nandini80** [PranabKumarSahoo/sql-dev-tools#5]
I can enhance the CSS of side bar and make it look more attractive 

<img width="425" alt="image" src="https://github.com/PranabKumarSahoo/sql-dev-tools/assets/121488571/ee40c5a2-e272-4a0f-b6ed-cdd08d60732d">

**Comment by PranabKumarSahoo** [comment]
Hello @Nandini80 , 
Thanks for creating an **issue** on this. ⭐

Here's my concern,
- As per the **SWOC rules**, we **(Project Admins)** can assign the tasks to the **Contributors** from 1st of Jan.
- But you can work on this now and keep me update your output through images/videos in the comment section. 
- And one more thing, don't make any PR now, you can do it when the program begins (On 1st Jan).

So don't worry, I'll assign this task to you with the tag on 1st of Jan.

Hope you got my points!

Thanks For Understanding! ✌️

---
### Feel free to ask any questions for further clarification.
**#Good Luck!✌️**

**Comment by PranabKumarSahoo** [comment]
Hello @Nandini80,

Today is the 1st of Jan. So, I'm officially assigning this task to you under **SWOC**. 
So feel free to start working on it. 
Please keep me updated on your progress through images/videos in the comment section.

For real-time communication and any immediate queries, you can join the [Discord](https://discord.gg/TSYH66px).

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on Discord. 

**#Good luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
Hello @Nandini80,

Thank you for your recent contributions to the project. I appreciate your efforts in enhancing Sidebar.

Just a friendly reminder, it would be great if you could keep me updated on your changes through images/videos in the comment section. 

This will help us ensure a thorough review and make the integration process smoother.

---
### Feel free to ask any questions for further clarification.

**#Good Luck!✌️**

**Comment by KhushiAgarwal-01** [comment]
I can work on this issue ?can it be assigned?
