### ISSUE TITLE
Add logo on navbar

### ISSUE THREAD

**Issue by Ishita928** [PranabKumarSahoo/sql-dev-tools#58]
A nice and simple logo can be added on navbar which looks relevant to the website 

![image](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/146575485/e9612787-2a95-4924-80f0-05bfcbf5c6bb)

**Comment by PranabKumarSahoo** [comment]
Hello @Ishita928, 

Thank you creating an issue on this. I appreciate your thoughts.
As of now we've no intention to add any logo, but if you've any logo preference then share with me. I'll think about it.

Thank you!
