### ISSUE TITLE
Better submit button design

### ISSUE THREAD

**Issue by Ishita928** [PranabKumarSahoo/sql-dev-tools#59]
submit button can be re-designed with better effects and visibility ,makes it look more appealing

![image](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/146575485/3251e7e0-e128-4ba1-ae6c-0e174de7202f)

![image](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/146575485/f166e00f-c988-4fdc-8acf-41a54c1e5a50)

**Comment by PranabKumarSahoo** [comment]
Hello @Ishita928, 

Thanks for creating an issue on this.
As this button doesn't seem relate with our website & also I'm aware that this button design issue is already implemented by some other Contributor. So I've to close this issue.

Feel free to create more issues/contribute more. 

 Thank you! ✌️
