### ISSUE TITLE
[ISSUE-01] DROP Constraint and Query Output

### ISSUE THREAD

**Issue by harshydv99** [PranabKumarSahoo/sql-dev-tools#6]
Hi @PranabKumarSahoo 

I checked through your website, it was demn good!

But I came across some issues, that I want to put forward:-

1. The DROP Constraint Section provides you with a Query which isn't defined for what Attribute to DROP.

2. The Output Query processed is also wrong in syntax, which can led to misinformation for the user!

![Screenshot 2024-01-01 140359](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/78367273/951fc875-a9e3-4adc-8b6b-0d54bac09a1b)

Please let me know your thoughts on this proposal, and if you have any specific preferences or additional requirements. I am eager to contribute to the continuous improvement.

Thank you for considering this request. I look forward to your feedback.

Best regards,
**Shera Bhai**

**Comment by PranabKumarSahoo** [comment]
Hello @shera-bhai,
Thanks for creating an issues on this.⭐

Here's my points after reviewing the code,
- I guess there's no syntax error or mistake in the code. Just the placeholder needs to be changed. 
- In the input, We've to enter the **Constrain name**(which is included with a ":") not **Table name**.
- So in the website, just the textbox placeholder needs to be changed as **_"Enter constrain name line by line...."_**
- So in the input, we've to enter the constrains.
- For example: `testdb1.dbo.OrderDetails: FK__OrderDeta__Order__2FCF1A8A` - This is a Constrain, after entering it you'll find the appropriate query like this `ALTER TABLE testdb1.dbo.OrderDetails DROP CONSTRAINT  FK__OrderDeta__Order__2FCF1A8A`.

**Hope you got my points!**

Anyway, I'm assigning this task to you. So feel free to start making changes on it.
Please keep me updated on your progress through images/videos in the comment section.

**PS: Keep me inform before you raised the PR.**

---

For any further clarification and any immediate queries, you can join the [Discord](https://discord.gg/TSYH66px).

**#Good luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
This issue's solved.
Now I'm closing this issue.✌️

**Comment by harshydv99** [comment]
No issues @PranabKumarSahoo
