### ISSUE TITLE
[Bugs]: Error Occurs in Side Navbar

### ISSUE THREAD

**Issue by PranabKumarSahoo** [PranabKumarSahoo/sql-dev-tools#60]
## Description:
The issue pertains to two main problems:
- When users click on any navigation links in the side navbar, an error message is displayed: "Cannot read properties of undefined (reading 'target')".
- The sidebar fails to close when users click outside of it.

## Demo
https://github.com/PranabKumarSahoo/sql-dev-tools/assets/118038201/341f2d79-8698-46d3-91ba-ae28707dcdb2

## Expected Behavior:
Clicking on a navigation link in the side navbar should smoothly navigate the user to the corresponding section of the website without encountering any errors. Additionally, clicking outside of the sidebar should close it as expected.

## Resolution:

1. Investigating the code associated with the side navbar to identify the root cause of the errors.
2. Implementing appropriate fixes to resolve the errors and ensure smooth navigation functionality.
3. Conducting thorough testing to validate that the issues have been effectively addressed and that the side navbar functions as expected.

## Additional:
Prior to addressing these issues, it is recommended to clone the recent version of the repository to ensure that all changes are based on the latest codebase.

**PS: First of all try to clone the recent version of the repo.**

**Comment by mayankbaranwal0** [comment]
@PranabKumarSahoo Is this issue available to work on?

**Comment by PranabKumarSahoo** [comment]
Hello @mayankbaranwal0,

Yes, this issue is available for you to work on. Your interest in addressing the errors in the side navbar is appreciated.

If you'd like to take on this task, feel free to clone the recent version of the repository and begin investigating the code associated with the side navbar. Once you've identified the root cause of the errors, you can proceed with implementing appropriate fixes to ensure smooth navigation functionality.

And also I'm giving you some info after reviewing the current state, I noticed some existing bugs in both the footer links and the sidebar links. It's possible that these issues are interconnected, as changes to the footer which is impacted the functionality of the sidebar.

Anyway, I'm officially assigning this task to you under **SWOC**. Feel free to start working on it.

Make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md) & [Pull Request Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/pull_request_template.md).

**#Happy Contribution! ⭐**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
Hello @mayankbaranwal0,

I wanted to remind you about the task assigned to you regarding the sidebar bugs. It's important to address these issues as soon as possible so that contributors can proceed with other pending tasks accordingly.

---
**Thank you! ✌️**

**Comment by PranabKumarSahoo** [comment]
Hello @mayankbaranwal0,

Please try to keep me update your work progress. 
If you face any challenges, please don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].
These bugs needs to be fix ASAP.

Thank you! ✌️

**Comment by PranabKumarSahoo** [comment]
Hello @sohan2213,

As the previous contributor has no response to this issue. So I'm officially assigning the task to you under**SWOC**.

Feel free to start working on it.

**Comment by PranabKumarSahoo** [comment]
Try to give a comment below on this so that I can assign you.

**Comment by Sohan2213** [comment]
Thank you @PranabKumarSahoo

**Comment by PranabKumarSahoo** [comment]
Now you can start working on it.

**Comment by PranabKumarSahoo** [comment]
Hey @Sohan2213,

What's your work progress!! Please keep me update. The bugs needs to be fix ASAP! ✌️

**Comment by Sohan2213** [comment]
@PranabKumarSahoo Yeah, I am getting on with it! I'll revert back by EOD.

**Comment by PranabKumarSahoo** [comment]
Hey @Sohan2213, what's your work progress! Please keep me update ASAP.

**Comment by PranabKumarSahoo** [comment]
Hey @Sohan2213, you didn't respond to this! 
So kindly give me the updates. 
Otherwise If you're not willing to do this, I'll reassign to some other contributor.
