### ISSUE TITLE
[Feature Request]: Integrate Dependabot for Automated Dependency Updates 

### ISSUE THREAD

**Issue by harmeetsingh11** [PranabKumarSahoo/sql-dev-tools#62]
### Description:

Keeping the project's dependencies up to date can be a challenging task, especially when done manually. To streamline and automate this process, we propose integrating Dependabot.

### Proposed Solution:
We need to add Dependabot to our project as it will significantly aid in keeping our dependencies current. Once activated, Dependabot will automatically submit pull requests (PRs) whenever there are outdated dependencies identified in our `package.json` file.

This automated approach will enhance our project's stability, security, and overall maintenance by ensuring that we are always using the latest and most secure versions of our dependencies.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I am willing to work on this issue
- [X] I am an SWOC 2024 contributor

**Comment by PranabKumarSahoo** [comment]
Hello @harmeetsingh11,

Thank you for proposing the integration of Dependabot for automated dependency updates. It's an excellent initiative to enhance the stability, security, and maintenance of our project.

As the project owner, I appreciate your willingness to work on this issue. Please go ahead and proceed with the implementation of Dependabot.

So, I'm officially assigning this task to you under **SWOC**. Feel free to start working on it.

Make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md) & [Pull Request Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/pull_request_template.md).

**#Happy Contribution! ⭐**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**
