### ISSUE TITLE
Incorrect spelling used.

### ISSUE THREAD

**Issue by sidharth2829** [PranabKumarSahoo/sql-dev-tools#7]
Spelling of coming is incorrect, "Comming" is being used.

<img width="290" alt="Screenshot 2024-01-01 at 6 26 09 PM" src="https://github.com/PranabKumarSahoo/sql-dev-tools/assets/111569459/5e4d2702-bf07-4286-ae37-0bea2f36f663">
<img width="1421" alt="Screenshot 2024-01-01 at 6 26 17 PM" src="https://github.com/PranabKumarSahoo/sql-dev-tools/assets/111569459/8d3dfb66-e5cf-4706-8dc7-9fe4c56c1308">
 Please assign this issue to me under SWOC'24

**Comment by PranabKumarSahoo** [comment]
Hello @sidharth2829,
Thanks for making an issue!

I assign this task to you. So start making changes on this. Remember to make your changes and keep me update your progress through images/videos in the comment section.

For real-time communication and any immediate queries, you can join the [Discord](https://discord.gg/TSYH66px).

---
**PS: Keep me inform before you raised the PR.**

**#Good Luck!✌️**

**Comment by sidharth2829** [comment]
I have corrected the spelling at both the places.

<img width="305" alt="Screenshot 2024-01-01 at 10 23 24 PM" src="https://github.com/PranabKumarSahoo/sql-dev-tools/assets/111569459/553f59e5-ad7b-4f28-b5f2-b53682772f20">


<img width="1406" alt="Screenshot 2024-01-01 at 10 23 11 PM" src="https://github.com/PranabKumarSahoo/sql-dev-tools/assets/111569459/e970f745-3679-4db0-bc02-ea5adaba4ea0">

**Comment by PranabKumarSahoo** [comment]
Cool @sidharth2829!⭐

Now, you can raise the PR.
