### ISSUE TITLE
Feature: Implement Automatic Branch Deletion After PR Merges

### ISSUE THREAD

**Issue by harmeetsingh11** [PranabKumarSahoo/sql-dev-tools#71]
### Description:
This issue addresses the need to automate branch deletion upon the successful merging of pull requests (PRs). Manually deleting branches after each PR merge can be cumbersome and prone to oversight. Implementing an automated solution will streamline the process and ensure a clean and organized repository.

### Steps to Implement:

Anyone with admin permissions to a repository can enable or disable the automatic deletion of branches.

1. Under your repository name, click  `Settings`. 

![1](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/130365071/9370d866-8ab4-4b52-8678-f5de5d5c8dd2)

2. On the `General` settings page, you can find a section called `Pull Requests`. Under `Pull Requests`, select Automatically delete head branches.

![2](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/130365071/c51eb5cd-2acf-4ba3-af36-874c2a5cdb1f)

**Comment by PranabKumarSahoo** [comment]
Hello @harmeetsingh11,

Thank you for opening this issue and proposing the implementation of automatic branch deletion upon PR merges. 
While I appreciate the suggestion and recognize its potential benefits, I've decided not to proceed with this feature at the moment.

Should the need for this functionality arise in the future, I will reopen the issue accordingly.

Once again, thank you for your contribution and understanding.
