### ISSUE TITLE
Bug: typo error

### ISSUE THREAD

**Issue by Soumya6Tiwari** [PranabKumarSahoo/sql-dev-tools#72]
while going across the website , I found a typo error in the word "COMMING" which should be spelled as "COMING"

**Comment by Soumya6Tiwari** [comment]
![Screenshot (1109)](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/117037441/7d705385-7443-4acb-ab61-68342f31e9ab)
@PranabKumarSahoo kindly assign me this issue.

**Comment by PranabKumarSahoo** [comment]
Hello @Soumya6Tiwari,

Thanks for raising this issue. 
But I'm aware that this issue is already been fixed, If you try to clone the recent version of the repo you can find that.

Thanks for understanding. Feel free to contribute more.

**Comment by Soumya6Tiwari** [comment]
@PranabKumarSahoo  sure  pranab you may be correct but even on cloning the recent version of the repo , though in the code it has been updated to coming but i think u have not merged it yet ,that's why it is showing typo again and again. kindly assign it to me if possible or else merge the previous one itself.
thanks

**Comment by PranabKumarSahoo** [comment]
Hello @Soumya6Tiwari,

Thank you for your diligence. 
While the fix has indeed been implemented in the codebase, but the updated version has not yet been deployed to the production environment.

Please note that our deployment process is not currently automated through **CI/CD Workflows**. 
As a result, the changes made in the repository may not immediately reflect on the live website.

Rest assured, once the program concludes and I'll finalize all contributions, I'll ensure that the latest version is deployed to the production environment. 

In the meantime, feel free to continue your valuable contributions.

Thank you for your understanding and dedication to the project.

**Comment by Soumya6Tiwari** [comment]
@PranabKumarSahoo  ok
