### ISSUE TITLE
Add footer 

### ISSUE THREAD

**Issue by Abhineshhh** [PranabKumarSahoo/sql-dev-tools#74]
As you can see there is no footer in your website 
![image](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/142514166/af239171-dc5c-4c1d-9202-897c812c045f)

so can i work in this issue under SWOC S4

**Comment by PranabKumarSahoo** [comment]
Hello @AbhineshJha, Thanks for creating this issue. I appreciate it.

If you try to clone the recent repository, the **Footer** is already implemented by some other contributor.

So I've to close this issue now.

---
Please feel free to create another issues/contribute more.

Thank you!
